### ISSUE TITLE
UpdateDataCommand

### ISSUE THREAD

**Issue by ghost** [mogilvie/GdprBundle#13]
Hi,

After failing at update command.

At first the command failed without having created a column gdpr_temp_password in the target entity.

Then comes an error message telling me about invalid keys :

I notice that the command import as as typo in naming from an array keys at 

line 218 :

$personalData = $result['originalData'];

line 350 :

$personalData = $result['newPersonalData'];

Fixed with small caps as awaited.

line 218 :

$personalData = $result['originaldata'];

line 350 :

$personalData = $result['newpersonaldata'];

Greetings.

Gérard

**Comment by ghost** [comment]
Environnement :
PHP 7.2.11
Symfony 3.4.18
doctrine-bundle 1.9.1
PostgreSQL 9.6.10

**Comment by mogilvie** [comment]
Hi, 
I haven't tried this with PostgreSQL.
Can you send a copy of the error message that you get?
Is it related to the camelcase array keys?

**Comment by ghost** [comment]
Hi, sorry for the late answer.

Here's the message :

```
$ php bin/console gdpr:update
Creating temporary columns
Creating personal data objects in 1 columns
 0/1 [>---------------------------]   0%
In UpdateDataCommand.php line 218:

  Notice: Undefined index: originalData

```
The lowercase in key has fixed the update command.

In my case i use snake_case for column name, usually doctrine will use camelCase.

**Comment by mogilvie** [comment]
Hi Gerardchic,
I've just done a bit of reading on PostgreSQL, it is likely the column naming convention.
Unfortunately I'm not running PostgreSQL on any of my servers. Please feel free to fork, mod, and submit a pull request.
I'll have time to look back into this in the new year.
Mark
