### ISSUE TITLE
Make a request on an encrypted data

### ISSUE THREAD

**Issue by nocklabdev** [mogilvie/GdprBundle#14]
Hello,

Is there a way to query on an encrypted data ?...
For example, I want to encrypt the `firstname` of the `User` Entity. But I still want to be able to query on it. How can we do that ?

Even if the data is not encrypted, how can we query on `Personal Data` field ? Do we have to reset all the options of the `Personal Data` field before passing the parameter to the `findOneBy` function ? Like this :

```php
// App\Entity\User.php
/**
* @ORM\Column(type="personal_data", length=256, options={
*     "format"="STRING",
*     "isSensitive"=false,
*     "isEncrypted"=true,
*     "idMethod"="DIRECT",
*     "basisOfCollection"="LEGITIMATE_INTEREST",
*     "identifiableBy"="Can be used to identify an individual if compared with third party database",
*     "providedBy"="The employee, the employer",
*     "purposeFor"="Used to identify the user and contact",
*     "retainFor"="P6Y",
*     "disposeBy"="ANONYMISE",
*     "methodOfReceipt"={"HTTP"},
*     "receiptProtection"={"TSS"},
*     "methodOfReturn"={"HTTP"},
*     "returnProtection"={"TSS"}
* })
*
* @GdprAssert\PersonalData({
*     @Assert\NotBlank
* })
*/
private $firstName;
```

```php
// App\Controller\DefaultController.php
$firstname = new PersonalData();
$firstname->setData($encryptor->encrypt('John'))
    ->setFormat(PersonalData::FORMAT_STRING)
    ->setIsSensitive(true)
    ->setIsEncrypted(true)
    ->setIdMethod(PersonalData::ID_METHOD_DIRECT)
    ->setBasisOfCollection(PersonalData::BASIS_LEGITIMATE_INTEREST)
    ->setIdentifiableBy('Can be used to identify an individual if compared with third party database')
;

$protectedUser = $em->getRepository(User::class)
    ->setEncryptor($encryptor)
    ->findOneBy([ 'firstName' => $firstname ]);
```

Thanks.
Greetings.

Matthieu

**Comment by mogilvie** [comment]
Hi Matthieu,
Search for a OneBy on a first name might throw more than one unique user, but the question is really about how to search PersonalData fields.
**For encrypted fields.**
How I do this in my own applications is to use the GdprTrait in the repository.
Within the repository, create a function for findOneByFirstName. The function would need to retrieve all users, decrypt the values, and filter the array collection.
**For unencrypted fields**
You might use LIKE to query for the first name with the PersonalData string in the table.
$qb
->andWhere('u.firstName LIKE :firstname')
->setParameter('firstname', $firstname);

**Comment by mogilvie** [comment]
Hi Matthieu,
Also above, you don't need to encrypt the name before you setData on the PersonalData object.  
There is a subscriber that catches the onFlush event and encrypts the value for you before it goes to the database (if the PersonalData is set as encrypted=true).
Similarly, a subscriber catches the postLoad event and decrypts the value when you load the entity from the database.
