### ISSUE TITLE
symfony 4 support

### ISSUE THREAD

**Issue by eventhorizonpl** [mogilvie/GdprBundle#2]
Hi,

Do you have any plans to implement symfony 4 support?

Best regards,
Michal

**Comment by mogilvie** [comment]
Hi Michal,

Short answer is yes, but in 3-6 months.

Long answer is that this GDPR bundle is part of a larger application which is still in development on Symfony 3.4.
I plan to migrate the entire application to Symfony 4 once I get everything to stable in 3.4. Thats probably 3-6 months away.

Feel free to fork and modify for your needs. I can merge any pull requests so long as they are backward compatible with 3.

Regards,
Mark

**Comment by danabrey** [comment]
Hi,

We've made a start on adding Symfony 4 support to this bundle, by removing the dependency on `symfony/symfony` and replacing it with dependencies on individual components. The composer.json in the GdprBundle references the symfony-4 branch of EncryptBundle. That would need to be changed if it were merged in.

**GdprBundle:** https://github.com/dailyinfo/GdprBundle/tree/symfony-4  
**EncryptBundle:** https://github.com/dailyinfo/EncryptBundle/tree/symfony-4

We also made a Flex recipe to automate some default configuration for EncryptBundle. It's using Flex's `generate(secret, 32)` to generate an encryption key. `generate()` uses bin2hex so not sure if that's suitable.

**Flex recipe:** https://github.com/dailyinfo/flex-recipes/tree/master/specshaper/encrypt-bundle/1.0

**Comment by mogilvie** [comment]
@danabrey    
Thanks for your contribution, I have merged your alterations.
If they're working satisfactorily for you then I will close this issue. 
Cheers,
Mark

**Comment by eventhorizonpl** [comment]
@danabrey 

Thank you for implementing symfony 4 support.

@mogilvie 

There are some small issues durring installation:
 - flex recipe probably doesn't work
 - bin/console encrypt:genkey command doesn't work here - I created key manually
 - roromix/spreadsheetbundle: dev-master - I'm not sure if dev-master dependency here is needed - probably ^1.0 mayb be enough

Anyway - it works great. Thank you!

**Comment by danabrey** [comment]
@eventhorizonpl @mogilvie I've opened a pull request on the Flex recipes contrib repository to add the recipe for EncryptBundle: https://github.com/symfony/recipes-contrib/pull/349

It will be available to anyone who has enabled the contrib repository as soon as it's merged.

GdprBundle doesn't require a recipe, as the only direct configuration required is to enable the bundle in the kernel, which Flex does by default.
